[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.3", features = ["http1"] }
tokio = { version = "1.44.2", features = ["rt", "rt-multi-thread", "macros"] }
axum-server = "0.7.1"

